version: "3"
   
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'basicdb'
      MYSQL_USER: 'ServerJon'
      MYSQL_PASSWORD: 'serverjon'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-basic
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: 'basicdb'
    depends_on:
      db:
        condition: service_healthy
